### PR TITLE
added license

### PR DESCRIPTION
**Pull request by MrNice**
Added an MIT license, copyright Cameron Boehmer. This will allow other people to use squirt in whatever way they want.

### CODE REVIEW

**Comment by nomicode** [comment]
Don't want to bikeshed this, but the Apache License 2.0 might be a better choice here. The Apache License comes with patent protection for all contributions and ensures that all contributions made to the project (via PRs and so on) are also available under the Apache License.

Some good explanation at the bottom of this post:

http://travisswicegood.com/2013/03/06/open-source-licenses/

> If I had [the licensing of Django] to do over again, it would be Apache today.

— Jacob Kaplan-Moss

**Comment by MrNice** [comment]
I've submitted another Pull Request ( https://github.com/cameron/squirt/pull/61 ) that includes a screenshot of this conversation. It's up to Cameron to decide which License to choose. Thanks for alerting me to these differences! 
- <3 MrNice

**Comment by cameron** [comment]
Thank you both for the thoughtful discussion. This question is what has been keeping me from being more actively engaged with contributors, whose work I very much appreciate. Leaning towards apache for @nslater's reasons and others. Will update you ASAP.

**Comment by MrNice** [comment]
@cameron Yeah, I vote for the Apache license as well. I was not at all sure what your intentions were with this project, but it's worth growing. The MIT license is great for once offs that you don't plan to maintain.

**Comment by cameron** [comment]
As contributors, how would you feel if I applied the Apache license, kept a tight reign on product and UX while being as welcoming as possible to technical contributions, and also used the product to, in as light-footed a manner as I can manage, promoted a related but closed-source paid service?

**Comment by nomicode** [comment]
The Apache license is important to get in as soon as possible, as it effectively licenses contributions under the same license. So this sort of thing can be a PITA to sort later.

I am interested in contributing to the project so long as it is run independently from whatever paid service you are offering. If features are rejected or removed because they would compete with a paid product, or the paid product interferes with the development of the OSS project in any, that would be a problem. And I would probably fork, or contribute to another project.

Promoting something on the homepage seems fine to me. Would we also link to other similar projects? I think it's nice to be as helpful as possible for users, even if that means linking to competitors sometimes. I have found that you get a lot of respect for it.

**Comment by MrNice** [comment]
@cameron There's a small chance I'd go Richard Stallman on you and release a competing project named 'Squint.'

Most likely I wouldn't care as long as, as @nslater said, there wasn't any interference from the closed source version. And yeah, you need to keep a tight reign on the design aspects.

For example, if you added a feature in the closed version, and I really liked that feature, I should be free to implement it in the free version.

**Comment by cameron** [comment]
Thank you for the feedback :) As I said, I'd love to open-source this and continue pushing the envelop on the quality of open-source products, but I'm going to take the day to do some thinking and make sure that it's really the right decision. Primarily, I'm concerned that my paid service will be a mobile-first experience, that I would be motivated to keep mobile features out of this project, and that contributors would naturally want to move in that direction. I'm balancing that against the awesomeness of throwing my weight behind this project as an open-source thing and taking the paid service in a direction that's less likely to collide. Will update you both ASAP, hopefully by EOD PST (San Francisco time). Thanks again for the discussion.

**Comment by cameron** [comment]
Okay! Game plan: Apache license for the bookmarklet source, which will remain in this repo. I will pull out the squirt.io page source into a private repo that consumes this one and contains whatever paid service promotions I want to add. That way, contributions to this library will go out to the existing/new users of squirt.io. (See https://ngrok.com/ for a similar project model.) Getting started tonight :)

Let the games begin!

**Comment by nomicode** [comment]
Cool.

**Pull request closed without merging**
