### PR TITLE
Αdd simple keyboard shortcuts (#2, #16, #31)

### PR DESCRIPTION
**Pull request by FMJansen**
I've added some code to add simple keyboard shortcuts;
- **_esc**_ will close the reader
- **_space**_ will pause the reader
- **_left arrow**_ will rewind 10 seconds

### CODE REVIEW

**Comment by nomicode** [comment]
Right arrow would be good for scrubbing forward.

Also: up and down arrow for increasing and decreasing speed.

**Comment by nomicode** [comment]
Is bb5ec7a meant to be included in this PR? Seems unrelated.

**Comment by FMJansen** [comment]
@nslater I agree on the other arrow actions, but I couldn't figure out how to do it as quickly. And no,  bb5ec7a shouldn't be included and only was added after pushing it, when this PR was already created. I'll try and give it its own PR.

**Comment by cameron** [comment]
Hey @FMJansen 

Thanks for the contrib, and sorry about the PR getting closed. I've separated the squirt bookmarklet source from the squirt.io source, and crossed a few wires in the process.

Feel free to resubmit your PR against the new files, or I may do some git foo to fix things up this weekend.

Thanks,
Cameron

**Comment by cameron** [comment]
This feature is live. Again, sorry about the PR kerfuffle. I hope it doesn't discourage you from further contributions.

**Pull request closed without merging**
